platform: linux

inputs:
  - name: source
  - name: version

outputs:
  - name: image

params:
  CONTEXT: source
  DOCKERFILE: ""
  BUILD_ARGS_FILE: version/version-file
  IMAGE_ARG_BASE_IMAGE: ""
run:
  path: build
