platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    tag: "0.11.1"

inputs:
  - name: source
  - name: version

outputs:
  - name: image

params:
  CONTEXT: source
  DOCKERFILE: ""
  BUILD_ARGS_FILE: version/version-file
  IMAGE_ARG_BASE_IMAGE: ""
run:
  path: build
