platform: linux

inputs:
  - name: cicd-source
  - name: source

outputs:
  - name: merged-values

params:
  CICD_VARS_FILES: assets/registry-image-defaultvars.yaml
  SOURCE_VARS_FILES: ci/pipeline-vars.yaml

run:
  path: bash
  args:
    - -exc
    - |
      declare -a varsFiles

      for f in ${CICD_VARS_FILES}; do
        varsFiles+=("cicd-source/${f}")
      done

      for f in ${SOURCE_VARS_FILES}; do
        varsFiles+=("source/${f}")
      done

      chmod 777 merged-values

      yq eval-all '. as $item ireduce ({}; . * $item )' "${varsFiles[@]}" | tee merged-values/values.yaml
