---
resources:
  - name: cicd-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/cicd.git
      private_key: ((cicd-git-deploy-private-key))
      paths:
        - pipelines/**
        - tasks/**
        - assets/**
  - name: go-backend-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/go-backend.git
      private_key: ((go-backend-deploy-private-key))
      paths:
        - ci/**
  - name: node-backend-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/node-backend.git
      private_key: ((node-backend-deploy-private-key))
      paths:
        - ci/**
  - name: frontend-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/frontend.git
      private_key: ((frontend-deploy-private-key))
      paths:
        - ci/**
  - name: yq
    type: registry-image
    icon: docker
    source:
      repository: registry.lab.verysmart.house/images/yq-task
      tag: "4"

jobs:
  - name: update-self
    serial: true
    plan:
      - get: cicd-source
        trigger: true
      - set_pipeline: self
        file: cicd-source/pipelines/manager-pipeline.yaml

  - name: update-yq-task
    serial: true
    plan:
      - get: cicd-source
        trigger: true
      - set_pipeline: build-yq-task-image
        file: cicd-source/pipelines/task-image-pipeline.yaml
        var_files:
          - cicd-source/assets/yq/pipeline-vars.yaml

  - name: update-go-backend
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: go-backend-source
            trigger: true
          - get: yq
            params:
              format: rootfs
      - task: merge-values
        image: yq
        file: cicd-source/tasks/merge-pipeline-vars.yaml
        input_mapping:
          source: go-backend-source
      - set_pipeline: build-go-backend
        file: cicd-source/pipelines/registry-image-pipeline.yaml
        var_files:
          - merged-values/values.yaml

  - name: update-node-backend
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: node-backend-source
            trigger: true
          - get: yq
            params:
              format: rootfs
      - task: merge-values
        image: yq
        file: cicd-source/tasks/merge-pipeline-vars.yaml
        input_mapping:
          source: node-backend-source
      - set_pipeline: build-node-backend
        file: cicd-source/pipelines/registry-image-pipeline.yaml
        var_files:
          - merged-values/values.yaml

  - name: update-frontend
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: frontend-source
            trigger: true
          - get: yq
            params:
              format: rootfs
      - task: merge-values
        image: yq
        file: cicd-source/tasks/merge-pipeline-vars.yaml
        input_mapping:
          source: frontend-source
      - set_pipeline: build-frontend
        file: cicd-source/pipelines/registry-image-pipeline.yaml
        var_files:
          - merged-values/values.yaml
