---
resources:
  - name: cicd-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/cicd.git
      private_key: ((cicd-git-deploy-private-key))
      paths:
        - pipelines/**
        - tasks/**
        - assets/**
  - name: core-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/core.git
      private_key: ((core-deploy-private-key))
      paths:
        - ci/**
  - name: frontend-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/frontend.git
      private_key: ((frontend-deploy-private-key))
      paths:
        - ci/**
  - name: helm-chart-source
    type: git
    icon: git
    source:
      uri: git@github.com:watchedsky-social/helm-chart.git
      private_key: ((helm-chart-deploy-private-key))
      paths:
        - ci/**


jobs:
  - name: update-self
    serial: true
    plan:
      - get: cicd-source
        trigger: true
      - set_pipeline: self
        file: cicd-source/pipelines/manager-pipeline.yaml

  - name: update-core
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: core-source
            trigger: true
      - set_pipeline: build-core
        file: cicd-source/pipelines/registry-image-pipeline.yaml
        var_files:
          - core-source/ci/values.yaml

  - name: update-frontend
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: frontend-source
            trigger: true
      - set_pipeline: build-frontend
        file: cicd-source/pipelines/registry-image-pipeline.yaml
        var_files:
          - frontend-source/ci/values.yaml

  - name: update-helm-chart
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: helm-chart-source
            trigger: true
      - set_pipeline: build-helm-chart
        file: cicd-source/pipelines/helm-chart-pipeline.yaml
        var_files:
          - helm-chart-source/ci/values.yaml
