anchors:
  - &standard_build_params  { CONTEXT: source }
  - &extra_build_params {{extra-build-params}} # Use {{ }} here for eager-substitution by the fly cli

resources:
  - name: source
    type: git
    public: true
    icon: git
    source: &source
      uri: git@github.com:watchedsky-social/((name)).git
      private_key: ((key))
  - name: tag-source
    type: git
    public: true
    icon: tag-check-outline
    source:
      << : *source
      tag_regex: ^v\\d+\\.\\d+\\.\\d+.*$
  - name: daily-trigger
    type: time
    public: true
    icon: timer-outline
    source:
      interval: 24h
      location: America/New_York
  - name: oci-build-task-image
    type: registry-image
    public: true
    icon: docker
    check_every: 168000h
    source:
      repository: concourse/oci-build-task
      tag: "0.11.1"
  - name: destination
    type: registry-image
    public: true
    icon: docker
    source:
      repository: registry.lab.verysmart.house/watchedsky/((name))
      username: ((harbor-user))
      password: ((harbor-password))

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - in_parallel:
          - get: source
            trigger: true
          - get: tag-source
            trigger: true
          - get: daily-trigger
            trigger: true
          - get: oci-build-task-image
            params:
              format: rootfs
      - load_var: version
        file: source/.git/describe_ref
        reveal: true
      - task: build-image
        image: oci-build-task-image
        privileged: true
        config:
          platform: linux
          inputs: [{ name: source }]
          outputs: [{ name: image }]
          caches: [{ path: cache }]
          params:
            << : [ *standard_build_params, *extra_build_params ]
          run: { path: build }
      - put: destination
        params:
          image: image/image.tar
          version: ((.:version))
          bump_aliases: true
