resources:
  - name: built-image
    type: registry-image
    icon: docker
    public: true
    source: {{target-image-config}}
  - name: source-image
    type: registry-image
    icon: docker
    public: true
    source: {{source-image-config}}
  - name: oci-build-task
    type: registry-image
    icon: docker
    public: true
    check_every: 168h
    source:
      repository: concourse/oci-build-task
  - name: build-scheduler
    type: time
    icon: timer-outline
    public: true
    source: ((rebuild-schedule))
  - name: cicd-source
    type: git
    icon: git
    public: true
    source:
      uri: git@github.com:watchedsky-social/cicd.git
      private_key: ((cicd-git-deploy-private-key))
      paths:
        - pipelines/**
        - tasks/**
        - assets/**

jobs:
  - name: build-task-image
    public: true
    serial: true
    plan:
      - in_parallel:
          - get: cicd-source
            trigger: true
          - get: source-image
            trigger: true
            params:
              format: oci
          - get: build-scheduler
            trigger: true
          - get: oci-build-task
            params:
              format: rootfs
      - task: build-image
        image: oci-build-task
        privileged: true
        config:
          platform: linux
          inputs: [{name: source}, {name: source-image}]
          outputs: [{name: image}, {name: tags}]
          caches: [{ path: cache }]
          params:
            DOCKERFILE: source/((dockerfile))
            IMAGE_ARG_BASE_IMAGE: source-image/image.tar
            BUILD_ARGS_FILE: source/((build-args-file))
          run: { path: build }
        input_mapping:
          source: cicd-source
      - put: built-image
        params:
          image: image/image.tar
        get_params:
          skip_download: true
