imageTag: "7.11.2"
concourse:
  web:
    clusterName: Watchedsky
    defaultGetTimeout: 10m
    defaultPutTimeout: 5m
    defaultTaskTimeout: 20m
    numGoroutineThreshold: 50000
    enableAcrossStep: true
    enableRedactSecrets: true
    externalUrl: https://ci.watchedsky.social
    localAuth:
      enabled: true
    noInputContainerPlacementStrategies: [fewest-build-containers, limit-active-containers]
    checkContainerPlacementStrategies: [fewest-build-containers, limit-active-containers]
    maxBuildLogsToRetain: 100
    defaultDaysToRetainBuildLogs: 14
    maxDaysToRetainBuildLogs: 60
    postgres:
      host: pg.lab.verysmart.house
      sslmode: require
      database: concourse
    kubernetes:
      enabled: true
      namespacePrefix: ws-secrets-
      teams:
        - main
    prometheus:
      enabled: true


    auth:
      cookieSecure: true
      duration: 168h
      mainTeam:
        config: |
          roles:
            - name: owner
              local:
                users: ["watchedsky-admin"]
              github:
                users: ["jghiloni"]
            - name: member
              github:
                orgs: ["watchedsky-social"]

        localUser: "watchedsky-admin"
        github:
          org: watchedsky-social
      github:
        enabled: true
web:
  enabled: true
  nameOverride: atc
  replicas: 3
  args: ["web"]

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

  keySecretsPath: "/concourse-keys"
  teamSecretsPath: "/team-authorized-keys"
  authSecretsPath: "/concourse-auth"
  postgresqlSecretsPath: "/concourse-postgresql"
  service:
    api:
      type: ClusterIP

    workerGateway:
      type: LoadBalancer

    prometheus:
      type: ClusterIP

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
      projectcontour.io/websocket-routes: /
    hosts:
      - ci.watchedsky.social

    ingressClassName: contour-external

    tls:
      - secretName: ci-watchedsky-social-tls
        hosts:
          - ci.watchedsky.social
worker:
  enabled: false

postgresql:
  enabled: false

rbac:
  create: true

secrets:
  create: false
